USE [master]
GO
/****** Object:  Database [RCHINO_DB]    Script Date: 24/05/2017 10:38:09 a.m. ******/
CREATE DATABASE [RCHINO_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RCHINO_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RCHINO_DB.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RCHINO_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RCHINO_DB_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [RCHINO_DB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RCHINO_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RCHINO_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RCHINO_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RCHINO_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RCHINO_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RCHINO_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RCHINO_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RCHINO_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RCHINO_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RCHINO_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RCHINO_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RCHINO_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RCHINO_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RCHINO_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RCHINO_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RCHINO_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RCHINO_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RCHINO_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RCHINO_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RCHINO_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RCHINO_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RCHINO_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RCHINO_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RCHINO_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [RCHINO_DB] SET  MULTI_USER 
GO
ALTER DATABASE [RCHINO_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RCHINO_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RCHINO_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RCHINO_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [RCHINO_DB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [RCHINO_DB]
GO
/****** Object:  Table [dbo].[TBL_USER]    Script Date: 24/05/2017 10:38:09 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TBL_USER](
	[ID] [varchar](50) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[LAST_NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[CRE_USER]    Script Date: 24/05/2017 10:38:09 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CRE_USER]
	@P_ID varchar(50),
	@P_NAME varchar(50),
	@P_LAST_NAME varchar(50)
AS
	INSERT INTO TBL_USER VALUES(@P_ID,@P_NAME,@P_LAST_NAME);

RETURN 0
GO
/****** Object:  StoredProcedure [dbo].[RET_USER_BY_ID]    Script Date: 24/05/2017 10:38:09 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RET_USER_BY_ID]
	@P_ID varchar(50)
AS
	SELECT ID,NAME,LAST_NAME
	FROM TBL_USER
	WHERE ID=@P_ID;
GO
USE [master]
GO
ALTER DATABASE [RCHINO_DB] SET  READ_WRITE 
GO
